language: node_js
node_js:
- stable
deploy:
  provider: heroku
  app: shareyour
  api_key:
    secure: cP0/aP1jKqR+ArWdJPhXQc7dv44KuImTRddQ4SS4X1Qirf5PiHcW9KbetWon2ucGlafobdX4OxDh0kM7j2X7NzioIUxDAuZPEmpqKZobvV9JOVsJC2QD+ok0TXvip/SSYlg0SvkU7dwcGp/rRzMr4f5sjzvl5jqEDDvJfvLKIVWfXWM6IgP7ugNxntWV+pccC9QMC7VyVR4OhorEUgGgh6fXZsAw9XxiPf6RwCrUEoTrvbC9GLoQFFTQ8zlF6QQzB9w6ikt5s7t5nEBmdhJi4p32GIhlrRB1PhW43h4qp1khrvYOUtw3PK07KsFYYzdyuxoARxbGb63wFbJizgBbjVQI4ihhbQ3kwaln+L6gGoItvxNO864OR9I0t77+6cAxmy0kLAYUsmuVXFIXZDBuWewqceOzThrGR4NZwhYonUrmzU1ucjNbyLTHAKQOQQT1MKG/eWQ1eTqQShDQ5YoEMH4NVL8fgTEiVKQnNAsYDxxPsrGFQ9G98f+Bpvyd5pHToeZGW+KsYx1HB140yuGsjbu3UBtaGTd41wsnRxKSKeP+yDjpB3un/9zilT/7HoPhqF3NZ6sg1AInV1y5v8l0Irc3O+MPGkIzeOWOC1GJwTTXQiQ+2VPabzHUxPHvXuRZsV29/JN03LQB8uODerjLbKEeAlWL6d26wb0+Bp2yiiM=
