language: node_js
node_js:
  - stable
deploy:
  provider: heroku
  app: shareyour
  api_key:
    secure: E3Tys/uyi2u7BVnFkW4NG3sYdTfEnO+m8MdPBq90m8UI1bv7ipErIYclArZC4+DUguU1fqoHFGEA5fVw8smtcLNC9TRro0nfuHWKReYOhQ9DA0Ju+r8lnkUi5n315KA3PnLCp2q0OaDeFxVW7MhGcTdXDaypnZXz4BVnxPRmqApSNcKmRt2j90LPBmZmODLTFUnFAjukWgew/9y5qD+R9+NL6FFRoknShKbj/aLPucTHFdFMCKx/fXbTAZCRfxbyj1lK+V2keNY2LQ198OZjfiiBRPKJ4uVY8dnU+zwL8BKvIXvNrSePzXRgf8afovy4QMLdOzb+iBjFaO5zDGISAERbZpx9dQTDlNEhAcQ5WXNgcJW35ZMhIzZ6xPIzt6M0jg6ESzhmf6QI/9sVlB9YWySJV1AlsdJEVsNVmaXnunqq490/q+PkDqSCy/MwmlYz7l6oxco3IZE2Aa6tthQo+ZifTshEqMLnvqWnn29derK4IQI0Jh/+h/Af3N+xP5Jv7swn9Zx9BN6YGMjYxm2wiLyrsyRvLyj5Zf9UFYtjUkkQXN72+IA3hA6pUPGwXVltJ2ZJFMbVighrDv8acUAGDKnzG4j+6FbOD6zWj4bSQwiVX9T4IAUZMBhwLD0qzmJTSnNVoY9XQPVrBaDvqeGiC2xUPbvKxZJtHRB/+dJuYcQ=
