language: node_js
node_js:
  - stable
deploy:
  provider: heroku
  app: shareyour
  api_key:
    secure: ibemo4NOURGJCb3q0C2/c3NFd/tPXgWGhPGhGXr3t/gORjZuFPYRnVlqhD315EwhCuwN/2d0f5o3N/sAWGXgisTHvMeVxBQW/wGCk6ERw0Hb6rF0UIaxkAW6vGs4dI1h80fjZ35BVRcNYC9bdR5WdI5341j2zonycWRzuu4NSGpoW4nNKm8iZHsO7ar/FaM/3NyQGFEFxZANruVxbPomhftNDFQKP5GwojO3d56oFsaQU7C1FOfbaFCGInssXiCvpOGLTUFAMspMLqhHEghh9JQxvcqwDDVSzOWemy0i6F+n2xXvrbA64URsMNWGYij/+1hRmYJthPipGgMM/DckT0InkHvP1aXh15UaPqayTZXfvJr/MSm1c3TxryJvNJt3M4iVS13/tfHvwNcVNy1hnd6u0ggsmArvXhj3Aqg7ajxQLwurJ27NqdzJErH8L8sCppDk1ABKYgDit2QiMDFlhMRCAkxriM660gxV+1qQRdeZIbLLycfBQQVupeHIai6DnSCk3YMIUblBF9+XMe+/vafN6rTh5fVD1XuqddwlBg7zw2rCgWpo0dTkjS6Td8bF2LwliPCt588H5VbPveMWZ4tjaY+XcElU1swhYsBpudY9rth9ZypoQ7H3YuFKJWcqqWrTWRxXhbwq+9+oKiucGKfCfDVg1j2dvPRWFZdfcco=
