language: node_js
node_js:
- stable
deploy:
  provider: heroku
  app: shareyour
  api_key:
    secure: ZzKy/slnHch6RaK3ReA7my8wY1lEPTJqQ+xB7q8G3cvZokMYCU0GewjdvjJQiloB1h/M3U7AxpUTgSj+bURMTsOF6V2O6F0Vh6N76BLQDsnG3TxUIKLfA2WUppw3Gs4cheFdQaHiYGbhdYtC8nSbtQO49rA9akO7lxku2SFUy6VIbXFdhZX/nDvvjUradA8K1rX9iU7OyidD3cqJ1VAMixO2+g+AmwPeGo1A6cAIlq6BELrN5Hg/DOSKh7AMQf0DGp8KG+h6pN4fEY8QgvyKISYL5JxTWOFsGxPADVc0qWkFfFGTn+KtieCULvSnuQSBxG2DjTdT096LHH6A8Qaq3f1fApx4bszncXJrkL93USQKp1e+BFms/+/5n+GDBgUVb/ynBKcvsOCUP3TuMcCI61NTut1E0ciUS7HtKWjMm5iyfmdJzGv7gnKu44wTf3NR61+IYOBKaY/n2Ir+Q3sOrIMtiFO0lahyp8WjoUAHd0YcZIbt6XB+ep1iKvA2yHtYSu77ydNwUiMivrGNMM92Iv8pDNoLBO37OI6CGWilFiyPdIZgPlmS6SD6BUI/CGifgAxEbVWpUlsXs8TYgXwI9aAc3Jfruv9ybNqTPEMVml2V3ghVBudBovpBB8tVAGMsAl2u9W6XkgN8Y6bz9lKv1vAgbVHTYR7LVrGlmlT5iXQ=
