language: node_js
node_js:
  - stable
deploy:
  provider: heroku
  app: shareyour
  api_key:
    secure: GZZsDxzdttnR/HBWAmIVUymeP2LNicad15Do2hNwhz3WzLEBBpdgKi8IBdMHTUEgI/OntvY+sH7JNzJeQgPnHzit30Hfh09Ozwjh+JTo/UMww5Mbotkm7JdF1DCHMvnFeV0PvBg+TGK70Ddvkw4yyzusSQHSm37MkYWQd8TvWs6BwIMOjZ5eEx07T3ZUOBgVIzLEB2FNKAD0JZtYVQYZUAOAA40qBW3PUr+192bAGlRHzG71G3OMiztD+P5Wi5mI/s/U4Z/fR05/4oOrBB+rS7jR38hIWDP6p4tMWtNOczClJFjjI85IDmt+oR/bVxGLj/ijFmTzz2sZlGI5RTCCl7VeWtoHZtw/UsCM28qkAZRoYlnFwYxjAiS/qowFZ3pD9sMQNIn+M0KnhTGOtQuVVMvwya2wHTbwiSbVfeTeElmqnBCWl98LW9+9wLYhMnuk3HdNOBlzafyqAHbPwWujEXNACJYg+pom2Xly5YwmTqZMf3/D7rbW0zQ7RuAd8yAc98Juc9NdOrDUAOBjNEZHWTT5bPn1eJuJ7po9GJz0Us+C7Gl2XMI7Kb9hvvOwhqZIibsKIXJ55GO9U8S6lOZbCg300S+r3wVyXdCSEXPz8Lc3aA4PoxDki/eBnMFX9Zh5iy0M1YVBBvp1DxgeDwiWnUIPEeCnkixkcskB6yQc80M=
